#port
server:
  port: 80
#spring resource
spring:
  datasource:
    url: jdbc:mysql:///ladmin?serverTimezone=GMT%2B8&characterEncoding=utf8
    username: root
    password: root
  thymeleaf:
    prefix: classpath:/templates/pages/

    cache: false
  task:
    execution:
       pool:
         core-size: 5
         max-size: 128
         queue-capacity: 128
         keep-alive: 6000
         thread-name-perfix: db-service-task-
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
  
  
mybatis:
  mapper-locations:
  - classpath:/mapper/*/*.xml
  
#log
logging:
  level:
   com.cy: debug
    